version: "3.8"
services:
    app:
        container_name: laravel-app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfileprod
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www
        networks:
            - laravel
    nginx:
        image: nginx:stable-alpine
        container_name: laravel-nginx
        ports:
          - '${APP_PORT}:${APP_PORT}'
        environment:
          PORT: '${APP_PORT}'
          DOMAIN: '${DOMAIN}'
        volumes:
            - ./:/var/www
            - ./docker/nginx/templates:/etc/nginx/templates
        networks:
            - laravel
        depends_on:
            - app
    node:
        image: node:23-alpine
        container_name: laravel-node
        volumes:
            - ./:/var/www/
        working_dir: /var/www/
        tty: true
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
